name: build app

on: workflow_dispatch
      
jobs:
  run:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: build
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          echo "-- $(pwd) --"
          ls
          echo "---"
          
          echo "::group::build"
          pip install pyinstaller
          pyinstaller --onefile --noconsole --hidden-import=tkinter --hidden-import=tkinter.filedialog --hidden-import=json --name app_1 main.py
          echo "::endgroup::"
          
          echo "-- $(pwd) --"
          ls
          echo "---"
          
          echo "-- $(pwd)/dist --"
          ls dist
          echo "---"

          gh release upload 0.1.0 dist/app_1.exe --clobber
